version: "3.9"



services:


# stable-diffusion-webui
  stable-diffusion:
    build:
      context: ./stable-diffusion-webui
      dockerfile: Dockerfile
    container_name: 'stable-diffusion'
    restart: always
    tty: true
    expose:
      - "7860"
    ports:
      - "7860:7860"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/ds_mlops/stable-diffusion-webui/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/fastapi:/root/fastapi/



# dbtの環境
#  dbt:
#    build:
#      context: ./dbt
#      dockerfile: Dockerfile
#    container_name: 'dash'
    # M1 macの場合
    #platform: linux/x86_64
#    restart: always
#    tty: true
    #expose:
    #  - "8050"
    #ports:
    #  - "8050:8050"
      # ほぼ同じ
      #- "127.0.0.1:8050:8050"
#    working_dir: '/root/'
#    volumes:
#      - /Users/tanakatouma/vscode/ds_mlops/dbt/src/:/root/src/
#      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/dash:/root/dash/

#secrets:
#  user_ssh_key:
#    file: $SSH_KEY_PATH