# python環境とjupyter環境を立ち上げる
version: "3.9"

services:
# jupyter環境
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    container_name: jupyterlab
    restart: always  # コンテナが停止した時に常に再起動する設定
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8080
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      # コンテナ側のポート
      # https://tkzo.jp/blog/difference-between-ports-and-expose-in-docker-compose/
      - "8080"
    ports:
      # アクセスIP(ここでは127.0.0.1なのでローカルループバックアドレス)からのみ8050ポートへの接続が許可され，コンテナ側の8050ポートへの接続が許可される
      # https://tkzo.jp/blog/difference-between-ports-and-expose-in-docker-compose/
      - "127.0.0.1:8080:8080"  
    volumes:
      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/root_jupyter:/root/.jupyter
      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/workspace:/workspace
     


    # GPUを使う場合の設定
    # environment:
    #   - "NVIDIA_VISIBLE_DEVICES=all"
    #   - "NVIDIA_DRIVER_CAPABILITIES=all"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
    
# python3の環境
  python3:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: 'python3'
    restart: always
    tty: true  # dockerが勝手に終了しないようにするのに必要
    volumes:
      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/ml/:/root/ml


# mlflowの環境
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: 'mlflow'
    restart: always
    command:
      - "mlflow"
      - "server"
      - "--backend-store-uri"
      - "/opt/outputs/mlruns"
      - "--default-artifact-root"
      - "/opt/outputs/mlruns"
      - "--host"
      - "0.0.0.0"
    ports:
      - 15000:5000
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/mlflow:/opt/outputs/mlruns




# Dashの環境
  dash-app:
    build:
      context: ./dash
      dockerfile: Dockerfile
    container_name: 'dash-app'
    restart: always
    tty: true
    expose:
      - "8050"
    ports:
      - "127.0.0.1:8050:8050"
    working_dir: '/root/'
    volumes:
      - /Users/tanakatouma/vscode/ds_mlops/dash:/root/dash/
     # - /Users/tanakatouma/Documents/Docker_volumes/ds_mlops/dash:/root/dash/
     # - .:/root/src/
      - ~/.zshrc:/root/.zshrc

#secrets:
#  user_ssh_key:
#    file: $SSH_KEY_PATH
